services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [v\Mb\Shared\Infrastructure\Doctrine\MbEntityManagerFactory, create]
    arguments:
      - driver:   '%env(MB_DATABASE_DRIVER)%'
        host:     '%env(MB_DATABASE_HOST)%'
        port:     '%env(MB_DATABASE_PORT)%'
        dbname:   '%env(MB_DATABASE_NAME)%'
        user:     '%env(MB_DATABASE_USER)%'
        password: '%env(MB_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: pruebatecnicaph.database_connection }
    public: true


  # Bonsais
  PruebaTecnicaPh\Mb\Bonsais\Domain\BonsaiRepository: '@PruebaTecnicaPh\Mb\Bonsais\Infrastructure\Persistence\DoctrineBonsaiRepository'

